### PR TITLE
ENH: Update conda, if running latest

### PR DESCRIPTION
**Pull request by effigies**
This adds the command `conda update -n base conda` just before cleanup, if `miniconda_version == 'latest'`.

Immediately, this deals with the fact that Miniconda released on version 4.4.10, while 4.4.11 is a critical upgrade, and will help neurodocker be resilient to the differences in conda and miniconda release cycles.

### CODE REVIEW

**Comment by effigies** [comment]
Seems to be an unrelated error.

**Comment by kaczmarj** [comment]
Thanks @effigies - the errors are related to docker-py releasing 3.x and me not accounting for it. Let me update `requirements.txt` (temporary fix) to restrict the compatible versions.

FYI neurodocker will support docker-py 3.x in the refactor (#143).

**Comment by kaczmarj** [comment]
@effigies - can you merge current master?

**Comment by kaczmarj** [comment]
@effigies - does this take care of https://github.com/conda/conda/issues/6811? Would this be necessary after miniconda 4.4.11 is released, assuming that release fixes the `IsADirectoryError` bug?

**Comment by effigies** [comment]
It should take care of conda/conda#6811. Travis updates conda, and is now passing in nipy/nipype#2455.

I don't know that there's going to be a 4.4.11. Check out the [archive](https://repo.continuum.io/miniconda/). It looks like they cut a release once a month.

**Comment by effigies** [comment]
Actually, should probably note that this doesn't seem to resolve the issue that caused us to drop off of 4.4. We still get version conflicts.

https://travis-ci.org/nipy/nipype/builds/344123797?utm_source=github_status&utm_medium=notification

So your call whether this is worth including.

**Comment by effigies** [comment]
Cancel that. I was looking at the wrong Travis run. This should be fixing nipy/nipype#2455 after all.

**Comment by kaczmarj** [comment]
This looks good to me. Thanks @effigies!

**Pull request merged**
