### PR TITLE
FIX: update spm version to 2018b

### PR DESCRIPTION
**Pull request by miykael**
SPM12's `dev` version was linking to version 2018a. But the corresponding file under [this link](https://www.fil.ion.ucl.ac.uk/spm/download/restricted/utopia/dev/) seems to be 2018b.

This PR updates the version where necessary.

### CODE REVIEW

**Comment by kaczmarj** [comment]
thanks for the pr @miykael - the 2018b mcr url will have to be added to the mcr template https://github.com/kaczmarj/neurodocker/blob/master/neurodocker/templates/matlabmcr.yaml

and the mcr version (it is 95) will have to be added here https://github.com/kaczmarj/neurodocker/blob/f52d03d2690996ddc67633f23a249b987feb5b0a/neurodocker/interfaces/interfaces.py#L140-L155

**Comment by miykael** [comment]
Thanks @kaczmarj , I added the proposed changes. I hope the tests pass now.

**Comment by kaczmarj** [comment]
this looks great, thank you so much @miykael!

**Comment by miykael** [comment]
Thank you for `neurodocker` :-)

**Pull request merged**
