### PR TITLE
Two minor typos

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Two typos I noticed trying to run the examples.

Actually, shouldn't it be `0.4.0rc0` though?

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Btw, I still get errors here:

```bash
docker run --rm kaczmarj/neurodocker:0.4.0rc0 generate singularity --base ubuntu:18.04 --pkg-manager apt --ants version=2.2.0

Traceback (most recent call last):
  File "/usr/bin/neurodocker", line 11, in <module>
    load_entry_point('neurodocker', 'console_scripts', 'neurodocker')()
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 349, in main
    subparser_functions[namespace.subsubparser_name](namespace)
  File "/opt/neurodocker/neurodocker/neurodocker.py", line 302, in generate
    print(recipe_obj.render())
  File "/opt/neurodocker/neurodocker/generators/singularity.py", line 108, in render
    self._fill_parts()
  File "/opt/neurodocker/neurodocker/generators/singularity.py", line 165, in _fill_parts
    impl(params)
  File "/opt/neurodocker/neurodocker/generators/singularity.py", line 32, in base
    "singularity base must be in the form `docker://...` or"
ValueError: singularity base must be in the form `docker://...` or `shub://...`
```

**Comment by jona-sassenhagen** [comment]
This:

`docker run --rm kaczmarj/neurodocker:0.4.0rc0 generate  docker   --base ubuntu:18.04 --pkg-manager apt --ants version=2.2.0 | docker build -` works, by the way.

**Comment by kaczmarj** [comment]
hi @jona-sassenhagen - thank you for the pull request. you are right that the docker image tag should not be `0.4.0` — that was me being hasty. and thank you for finding the typos!

the `--run-bash` option will be added in #160. can you please add `--run-bash` back into this pull request?

then i can merge this PR and I will update the docker image tags in the readme to 0.4.0rc1 and release 0.4.0 release candidate 1. does that sound good?

by the way, you can always use `kaczmarj/neurodocker:master`. i purposely do not include a `latest` tag because i want users to use a versioned image.

**Comment by jona-sassenhagen** [comment]
Done.

``--no-check-urls`` was also giving me errors, is it also gonna come in some PR?

**Comment by kaczmarj** [comment]
@jona-sassenhagen - yes, i am updating those examples in #160. i'll merge that and release 0.4.0rc1 shortly after.

**Comment by jona-sassenhagen** [comment]
Great.

**Pull request merged**
