### PR TITLE
FIX: small updates to reprozip trace runner

### PR DESCRIPTION
**Pull request by miykael**
Quick code fixes discussed during the Nipype 2.0 sprint.

### CODE REVIEW

**Comment by miykael** [comment]
Not sure why it is crashing. If you have a quick solution to this, I'm happy to change it.
But if you want to leave those changes for a later time, feel free to cancel this PR.

**Comment by remram44** [comment]
You could simply use `continue_="--overwrite"` line 64. That way reprozip would overwrite the trace directory without asking, for the first command.

**Comment by kaczmarj** [comment]
thanks @remram44!

@miykael - would you like to add this change?

**Comment by miykael** [comment]
Happy to do so @kaczmarj. Thanks for the solution @remram44.
I've tried it with https://github.com/kaczmarj/neurodocker/pull/233/commits/17a6a187394952d0f2d37047188460c17209e55e, but I'm not sure if this is the solution that you ment?

**Comment by remram44** [comment]
I meant something like this:
```bash
    if [ "$cmd" == "${cmds[0]}" ]; then
        continue_="--overwrite"
    else
        continue_="--continue"
    fi
    reprozip_cmd="${reprozip_base_cmd} ${continue_} ${cmd}"
```

**Comment by miykael** [comment]
Of course! Sorry, I didn't read well enough to see the difference between `overwrite` and `continue`...
This should be fine now.

**Comment by kaczmarj** [comment]
thanks @miykael and @remram44 !

**Pull request merged**
