### PR TITLE
creating an fsl startup script and an entry point in dockerfile in or…

### PR DESCRIPTION
**Pull request by djarecka**
…der to get environmental variable when running docker without `bash`, e.g. `docker run image python`

This solves my problem with running pytest `docker run -it -v $PWD:/home myimage_test  pytest`. 
Without creating the entry point you have to run pytest command from bash like that `docker run -it -v $PWD:/home myimage_test bash -c ". /etc/profile.d/fsl.sh; pytest /home/tests_regression/test_spm_realign_regr.py"`

Startup scripts might be needed for another packages.

### CODE REVIEW

**Comment by kaczmarj** [comment]
Hi @djarecka - I had a fix for this in mind (#19) which would allow users to add arbitrary Dockerfile instructions. I am hesitant to apply an entrypoint specifically for FSL because it might interfere with other software that is installed.

I will try to implement #19 today.

**Comment by kaczmarj** [comment]
Hi @djarecka - I implemented this. It's in the [arb-instruct](https://github.com/kaczmarj/neurodocker/tree/arb-instruct) branch. The instructions are always added at the end of the Dockerfile (I don't think I'll change that behavior).

Let me know if that doesn't work for you.

Here is a command-line example:

```shell
neurodocker -b ubuntu:17.04 -p apt \
    --fsl version=5.0.10 \
    --instruction='RUN echo "Hello, World!"' \
    --instruction='ENTRYPOINT ["entrypoint.sh"]'
```

returns...

```dockerfile
FROM ubuntu:17.04

ARG DEBIAN_FRONTEND=noninteractive

#----------------------------
# Install common dependencies
#----------------------------
RUN apt-get update -qq && apt-get install -yq --no-install-recommends bzip2 ca-certificates curl unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#------------------
# Install FSL 5.0.10
#------------------
RUN curl -sSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-5.0.10-centos6_64.tar.gz \
    | tar zx -C /opt \
    && cp /opt/fsl/etc/fslconf/fsl.sh /etc/profile.d/ \
    && FSLPYFILE=/opt/fsl/etc/fslconf/fslpython_install.sh \
    && [ -f $FSLPYFILE ] && $FSLPYFILE -f /opt/fsl -q || true
ENV FSLDIR=/opt/fsl \
    PATH=/opt/fsl/bin:$PATH


#--------------------------
# User-defined instructions
#--------------------------

RUN echo "Hello, World!"

ENTRYPOINT ["entrypoint.sh"]
```

**Comment by kaczmarj** [comment]
@djarecka - (sorry for all the messages) I fixed the real problem with the FSL installation (changes are now in master). Before the `fsl.sh` script was being copied to `/etc/profile.d`, which I thought would be sourced each time the container is run. It turns out that this is not the case, so now the installation sources `fsl.sh` directly.

Let me know if you are still having issues.

**Comment by kaczmarj** [comment]
@djarecka - the issue with FSL's environment variables should be fixed now. Neurodocker creates a bash script used as the default entrypoint (`/neurodocker/startup.sh`), and FSL's bash file is sourced in that entrypoint script. Let me know if you are still running into issues.

**Comment by djarecka** [comment]
Nice!

**Pull request closed without merging**
